US 12 -  Parents should not be too old
seige13/ssw-555-gedcom pull request #56
Opened 2017-10-03 19:38 UTC by seige13

Mother should be less than 60 years older than her children and father should be less than 80 years older than his children

* Small refactor of family unit test class so we don't have to redeclare objects for each method
* Fixes #11

2017-10-04 21:39 UTC, jsaterfiel requested changes

2017-10-04 21:39 UTC, jsaterfiel commented on gedcom/test_families.py
> +        self.fam.families.clear()
Not sure what this is for.  We have a setup and tear down which deletes and recreates the fam object already.

2017-10-04 21:39 UTC, jsaterfiel commented on gedcom/families.py
> +                return False
Don't need to return false here as nothing uses this return value.  For testing you should be using .validate() and checking the messages returned as this is a private method.

2017-10-06 02:06 UTC, cthaden approved these changes

2017-10-13 00:00 UTC, jsaterfiel approved these changes

2017-10-13 00:00 UTC, merged