US29 and US30 - Add print for married and deceased individuals
seige13/ssw-555-gedcom pull request #71
Opened 2017-10-26 18:59 UTC by seige13

Add print for married and deceased individuals

Fixes:
* #23 and #24

2017-10-26 19:31 UTC, jsaterfiel commented
Where's the tests for the user stories?

2017-10-26 19:32 UTC, jsaterfiel requested changes
Please add unit tests for user stories along with test cases in the acceptance gedcom file

2017-10-29 16:08 UTC, cthaden approved these changes

2017-10-29 16:37 UTC, jsaterfiel approved these changes

2017-10-29 16:37 UTC, merged